[build]
  base = "/"
  publish = "dist/"
  command = "NODE_OPTIONS=--openssl-legacy-provider npm run build"
  functions = "my_functions/"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[context.production.environment]
  NODE_VERSION = "16"